### ISSUE TITLE
follow-up(SystemMessageGroup) - improve behaviour

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#10758]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Follow-up / Regression fixes for #9777:

- [ ] Showing in LeftSidebar in conversation
- [ ] Fixing the Unread messages marker (may be hidden in the list)
- [x] Disable/remove/rework sorting system messages in the group

Feel free to add items to the list

**Comment by DorraJaouad** [comment]
Just a thought if we are keeping the read marker logic : 
What if we just keep the combined system message not collapsed as long as `LastReadMessageId` is in one of its messages ?

For LeftSidebar, either we do the same ( keep it not collapsed by default if it is the last message) or we can reflect this "nested" format ( collapsed message > combined message > MessagesSystemGroup) in the store so we can get the combined message and render it in Conversation.

**Comment by nickvergessen** [comment]
This is solved for now, right?

**Comment by DorraJaouad** [comment]
No, only sorting messages was solved.

**Comment by nickvergessen** [comment]
Left sidebar I think not grouping is okay.

The readmarker could be because of mixed up sorting. But then it would be live already on our server and others reported just again that it happens, so yeah might still have issues.

**Comment by DorraJaouad** [comment]
The thing is the grouped message is not actually a message where we can get its id. It is not stored but kinda "computed" ? 
It should be added to the store so we can get it in LeftSidebar.

**Comment by nickvergessen** [comment]
> It should be added to the store so we can get it in LeftSidebar.

Or we keep it simple and only show non-combined messages as last message? Simplicity is key!

**Comment by DorraJaouad** [comment]
> Or we keep it simple and only show non-combined messages as last message? 

The issue was that, because in the chat view, you don't see the last non-combined message but you see its "parent" combined message. 

A simple solution would be the following: 
Always show grouped system messages NOT collapsed by default if they are the last messages in the chat. 

@Antreesy  what do you think ?

**Comment by nickvergessen** [comment]
> The issue was that, because in the chat view, you don't see the last non-combined message but you see its "parent" combined message.

We can change that to have the last message id instead of the first as pointed out before :)
