### ISSUE TITLE
Warn user when https is blocking permission to camera/mic

### ISSUE THREAD

**Issue by notklaatu** [nextcloud/spreed#930]
## Steps to reproduce
1. log in to your instance of example.com/nextcloud
2. enable Talk app
3. make a video call to your friend

### Expected behaviour
Browser should connect to camera and mic. Failing that, an error ought to be shown to the user ("Error accessing your camera and/or microphone. Note: NextCloud Talk requires an HTTPS connection.")

### Actual behaviour
Browser fails to access your camera and mic with error message saying that it failed to access camera and mic (which itself is obvious, since the user's camera and mic are not working). 

I'm not sure if there's a way to detect why the camera and mic are inaccessible, but some text somewhere outside of Github issues explaining that HTTPS is required would be helpful.

**Comment by nickvergessen** [comment]
We have a dedicated error message for this. Not sure where this went to.

**Comment by danxuliu** [comment]
I have tested on Nextcloud 16.0.5 with Talk 6.0.4 and on Nextcloud 17.0.1 with Talk 7.0.2 and the message _Access to microphone & camera is only possible with HTTPS: Please move your setup to HTTPS_ was shown as expected on Firefox 70 and on Chromium 68 and Chromium 75. This may have been (indirectly) fixed in #1729.

Note that on older Firefox versions no message was shown because [microphone and camera worked on insecure contexts before Firefox 68](https://blog.mozilla.org/webrtc/camera-microphone-require-https-in-firefox-68/).

Due to all of the above I will close this issue. Feel free to reopen if it happens again in a recent Talk version, and in that case please provide the Nextcloud, Talk and browser version where it happened. Thanks! :-)

**Comment by dsmic** [comment]
hi,
I still have this issue on iOS. As the nextcloud talk app does not support conferences without login, using a webbrowser is needed. Safari does not support webrtc I tried chrome and firefox.

both have the issue blocking microphone on not https.

chrome: 80.0.398795
safari: Version 23.0 (17297)

Please let me know, if you need more infos,

Detlef

**Comment by nickvergessen** [comment]
The only solution is to move to https which you should do anyways

**Comment by dsmic** [comment]
Thanks, but I am on https as indicated by all three browsers

**Comment by nickvergessen** [comment]
Well but if you are on HTTPS you shouldn't get the browser warning that your camera+mic can not be accessed because the website is not using HTTPS.

Mind to share a link to a conversation on your instance?

**Comment by dsmic** [comment]
I would, but can not find a way to contact you in private.

I do have this problem only on iOS, chrome (also version 80) and firefox (74) on ubuntu are fine.
You might contact me with my e-mail address on physik.de.

Thanks

**Comment by nickvergessen** [comment]
`<my github name>@nextcloud.com`

**Comment by nickvergessen** [comment]
So we tested this quickly and it seems to work fine.
But we noticed that your cert was renewed yesterday and is now TLS 1.3
Is it possible you tried it with another cert before? Because iOS is not accepting TLS <1.3 anymore.
